version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  back:
    build: ..
    command: sh -c "poetry run flask db upgrade && poetry run flask load-fixtures && poetry run gunicorn --bind 0.0.0.0:3000 cat_shop:application"
    volumes:
      - ../static/:/code/static/
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=cat_shop
      - PYTHONPATH=/code/cat_shop/
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:8000"
    volumes:
      - ../static/:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - db


volumes:
  postgres_data: