#!/bin/bash

HAS_ERRORS=0
LINT_EXCLUDE_PATTERN="migrations"

# -vE - is invert-match + extended-regexp
for FILEPATH in $(git diff --name-only origin/main HEAD -- | grep "^cat_shop/.*\.py$" | grep -vE "$LINT_EXCLUDE_PATTERN"); do
    # skip file if it was deleted
    [ ! -f "$FILEPATH" ] && continue
    # for debug purposes
    echo "$FILEPATH";
    if ! "$1" "$FILEPATH" "${@:2}";
    then
      # store exit code for error check later on
      HAS_ERRORS=1
    fi
done

exit $HAS_ERRORS
