"""empty message

Revision ID: 057dbeb4b5aa
Revises: 
Create Date: 2022-06-05 13:52:01.025947

"""
import sqlalchemy as sa
from alembic import op

from db.models import TSVector

# revision identifiers, used by Alembic.
revision = "057dbeb4b5aa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """CREATE OR REPLACE FUNCTION my_to_char(some_time timestamp)
       RETURNS text
     AS
     $BODY$
         select to_char($1, 'yyyy mm dd');
     $BODY$
     LANGUAGE sql
     IMMUTABLE;"""
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "breeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column(
            "__ts_vector__",
            TSVector(),
            sa.Computed("to_tsvector('russian', coalesce(name,''))", persisted=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_breed___ts_vector__",
        "breeds",
        ["__ts_vector__"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "kitties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("breed_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("image", sa.String(length=100), nullable=True),
        sa.Column("birthday", sa.DateTime(), nullable=True),
        sa.Column(
            "__ts_vector__",
            TSVector(),
            sa.Computed(
                "to_tsvector('russian', coalesce(name,'') || ' ' || my_to_char(coalesce(birthday)) || ' ' || coalesce(description,''))",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["breed_id"],
            ["breeds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_kitty___ts_vector__",
        "kitties",
        ["__ts_vector__"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_kitty___ts_vector__", table_name="kitties", postgresql_using="gin"
    )
    op.drop_table("kitties")
    op.drop_index("ix_breed___ts_vector__", table_name="breeds", postgresql_using="gin")
    op.drop_table("breeds")
    # ### end Alembic commands ###
