"""empty message

Revision ID: 1c1e47883ae4
Revises: 057dbeb4b5aa
Create Date: 2022-06-07 12:40:43.615365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1e47883ae4'
down_revision = '057dbeb4b5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kitties', 'breed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kitties', 'image',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint('kitties_breed_id_fkey', 'kitties', type_='foreignkey')
    op.create_foreign_key(None, 'kitties', 'breeds', ['breed_id'], ['id'], onupdate='restrict', ondelete='restrict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kitties', type_='foreignkey')
    op.create_foreign_key('kitties_breed_id_fkey', 'kitties', 'breeds', ['breed_id'], ['id'])
    op.alter_column('kitties', 'image',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('kitties', 'breed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
